FROM ubuntu:26.04


# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y \
    wget \
    bzip2 \
    make \
    unzip \
    cppcheck \
    clang-format-21 \
    git \
    xz-utils \
    openocd \
    usbutils \
    && rm -rf /var/lib/apt/lists/*

# Download the toolchain and unzip it into /opt/toolchain/
RUN mkdir -p /opt/toolchains \
    && wget -q https://gitlab.arm.com/api/v4/projects/tooling%2Fgnu-toolchains-for-arm/packages/generic/gnu-toolchain/15.3.rel1/arm-gnu-toolchain-15.3.rel1-x86_64-arm-none-eabi.tar.xz \
    && tar -xf arm-gnu-toolchain-15.3.rel1-x86_64-arm-none-eabi.tar.xz -C /opt/toolchains/ \
    && rm arm-gnu-toolchain-15.3.rel1-x86_64-arm-none-eabi.tar.xz

# Add path to the toolchain to the system PATH
ENV PATH="/opt/toolchains/arm-gnu-toolchain-15.3.rel1-x86_64-arm-none-eabi/bin:${PATH}"

USER ubuntu
WORKDIR /home/ubuntu
