FROM ubuntu:22.04


# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y wget bzip2 make unzip cppcheck clang-format-12 git xz-utils \
    && rm -rf /var/lib/apt/lists/*

# Download the toolchain and unzip it into /opt/toolchain/
RUN mkdir -p /opt/toolchains \
    && wget -q https://gitlab.arm.com/api/v4/projects/tooling%2Fgnu-toolchains-for-arm/packages/generic/gnu-toolchain/13.2.Rel1/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi.tar.xz \
    && tar -xf arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi.tar.xz -C /opt/toolchains/ \
    && rm arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi.tar.xz

# Add path to the toolchain to the system PATH
ENV PATH="/opt/toolchains/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin:${PATH}"

# Create a non-root user named "ubuntu"
# But put in root group since GitHub actions needs permissions
# to create tmp files.
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo \
    -u 1001 ubuntu

USER ubuntu
WORKDIR /home/ubuntu
