
on: [push]

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: nikskarabot/multi_fx_board-dev_env:25.9.2026
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: make format && git diff --quiet
      - run: make cppcheck
      - run: make
